### ISSUE TITLE
Stray brace?

### ISSUE THREAD

**Issue by danielhoherd** [mlichvar/ntpstat#1]
https://github.com/mlichvar/ntpstat/blob/941b0660f9500aa96a5d006f133073c0bfe4aa3d/ntpstat#L110

Is this brace supposed to be here? If so, for uniformity wouldn't it be better placed within the double quotes?

EDIT: Maybe it was pasted from here: https://github.com/darkhelmet/ntpstat/blob/master/ntpstat.c#L89

**Comment by mlichvar** [comment]
Yeah, it was probably pasted from the C code. Thanks again.
