### ISSUE TITLE
ntpstat and Older Versions of Mac OS X

### ISSUE THREAD

**Issue by RobK88** [mlichvar/ntpstat#7]
I just wanted to let you know that your version of `ntpstat` also runs fine on MacOS.  But on older versions of Mac OS X, one must install and use `gawk` instead  of`awk` (that comes with older versions of Mac OS X).  Otherwise, the following error appears:

```
rob$ ./ntpstat
awk: calling undefined function and
 input record number 1, file 
 source line number 1
synchronised to unknown source at stratum 2
   time correct to within 60 ms
   polling server every 1024 s
Grinchs-Mac-Pro:ntpstat-master rob$
```

I simply patched your script by replacing `awk` with `gawk` and your `ntpstat` script worked without any errors on my old Mac running Lion.  (Note: `gawk` was perviously installed on my Mac.   One can easily do that via Homebrew or Macports).

In your script for `ntpstat`, you may want to consider testing whether `awk` is working in your script and, if not, use `gawk` instead.  

Alternatively, please consider noting on this website that your `ntpstat` script will not run with older versions of `awk` and in that case , the quick fix is simple -  install a recent version of`gawk` on the Mac and either manually patch your `ntpstat` script by changing all occurrences of `awk` to `gawk` or just replace `awk` with `gawk` on the Mac in question by creating a symlink between `awk` and `gawk`. (I prefer patching your script since there is always a small possibility  that replacing `awk` with `gawk` on an older Mac may break other scripts and programs that rely on the old `awk`).

**Comment by mlichvar** [comment]
Do you know which `awk` command failed? Maybe it could be modified to work both with `gawk` and old macOS `awk`.

**Comment by mlichvar** [comment]
Hm, now I see it's the `and` function and searching on web indicates the macOS `awk` might be missing also the `strtonum` function.
